# Docker compose file that runs:
# - Postgres
# - Adminer as Postgres UI
# - Mailhog as UI for testing mails

version: '3.1'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: lopenling
      POSTGRES_USER: lopenling
      POSTGRES_DB: lopenling
    network_mode: host
    volumes:
      - lopenling_db:/var/lib/postgresql
    # ports:
    #   - 5432:5432

  adminer:
    image: adminer
    network_mode: host
    # ports:
    #   - 8085:8080

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none' # disable saving logs
    network_mode: host
    # ports:
    #   - 1025:1025 # smtp server
    #   - 8025:8025 # web ui

volumes:
  lopenling_db:
