services:
- type: web
  name: hasura
  env: docker
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_METADATA_DATABASE_URL
    fromDatabase:
      name: hasura
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: PORT
    value: 10000
# for your Hasura instance. The value is visible under
# Environment on the Render dashboard.
  - key: HASURA_GRAPHQL_ADMIN_SECRET
    generateValue: true
  - key: HASURA_GRAPHQL_JWT_SECRET
    value: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDDTCCAfWgAwIBAgIJdIvkpB8Lr3lXMA0GCSqGSIb3DQEBCwUAMCQxIjAgBgNV\nBAMTGWRldi0temRpZnFrcS51cy5hdXRoMC5jb20wHhcNMjAwOTA0MTcyNzEwWhcN\nMzQwNTE0MTcyNzEwWjAkMSIwIAYDVQQDExlkZXYtLXpkaWZxa3EudXMuYXV0aDAu\nY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0CTtkzIO/UGKy8NL\nj9h/HamVH4i5sqKiK1Fq6RdRYtFhh/qWj0SkJETlT7lLEPo4aGZ1/VJIgEtLCLUX\nzWC1lorxosmEcbnjJ3N2xeE/gY8uv7+MsstPZOp0Ke6WXHyzZNkSXYyxhoa/70k2\nF8eutZXwYhTOLhOG8NOn7cMvKdTVWsK31vYqPiEf41h4kn5y2/ThrftXreKK5DQj\nTyleEIn3V/YRkNWinG12ySCLE+4Du1+QMtRhXXW+rSUTPBVmS2dRY6lpGvA3vNRw\nYd5to1x9qohfXbil4sgHIHTgf7sgPiDGLyXUOfWJqyn4ftNL7diI3qzWOmukBSlZ\nJ3MZGwIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ7oTRyntPx\n/kfXVw7w4ziUT2qUvjAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEB\nAKMyxaC485m0mkMQVS0WKlJoBpik5xpTqgTutGUsDcpVMOR5WeozUkFAoVA0Bh1b\ne1WCBpvSfkT5X7nPmVYuDJJ3h4OAy2BrmMv0oFGtuHQ/GnCng6tz++gdfl1zi74E\nExsKK0SsZj55O6Docm0y+FKCu1GiQ1Td4JowBHLw4qN0HUMashXte+M12wRmhfIh\ne9Pi8stQwNWxVXPorLegaHCkMl9sl2g9L7dW05qxIgRdp/eEG1p3MDoTG0ykSXDR\nTswlbnPoSfBi9Ile2f683a6TSocAdJgCfgvqGUinGTEkcOjLIvFjvbja9IV4/TpN\n1ztGdtudfXQ0hmhBqS/qagw=\n-----END CERTIFICATE-----"}'
databases:
- name: hasura
