version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.3.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: Lopenling@Secret123
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDDTCCAfWgAwIBAgIJdIvkpB8Lr3lXMA0GCSqGSIb3DQEBCwUAMCQxIjAgBgNV\nBAMTGWRldi0temRpZnFrcS51cy5hdXRoMC5jb20wHhcNMjAwOTA0MTcyNzEwWhcN\nMzQwNTE0MTcyNzEwWjAkMSIwIAYDVQQDExlkZXYtLXpkaWZxa3EudXMuYXV0aDAu\nY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0CTtkzIO/UGKy8NL\nj9h/HamVH4i5sqKiK1Fq6RdRYtFhh/qWj0SkJETlT7lLEPo4aGZ1/VJIgEtLCLUX\nzWC1lorxosmEcbnjJ3N2xeE/gY8uv7+MsstPZOp0Ke6WXHyzZNkSXYyxhoa/70k2\nF8eutZXwYhTOLhOG8NOn7cMvKdTVWsK31vYqPiEf41h4kn5y2/ThrftXreKK5DQj\nTyleEIn3V/YRkNWinG12ySCLE+4Du1+QMtRhXXW+rSUTPBVmS2dRY6lpGvA3vNRw\nYd5to1x9qohfXbil4sgHIHTgf7sgPiDGLyXUOfWJqyn4ftNL7diI3qzWOmukBSlZ\nJ3MZGwIDAQABo0IwQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ7oTRyntPx\n/kfXVw7w4ziUT2qUvjAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEB\nAKMyxaC485m0mkMQVS0WKlJoBpik5xpTqgTutGUsDcpVMOR5WeozUkFAoVA0Bh1b\ne1WCBpvSfkT5X7nPmVYuDJJ3h4OAy2BrmMv0oFGtuHQ/GnCng6tz++gdfl1zi74E\nExsKK0SsZj55O6Docm0y+FKCu1GiQ1Td4JowBHLw4qN0HUMashXte+M12wRmhfIh\ne9Pi8stQwNWxVXPorLegaHCkMl9sl2g9L7dW05qxIgRdp/eEG1p3MDoTG0ykSXDR\nTswlbnPoSfBi9Ile2f683a6TSocAdJgCfgvqGUinGTEkcOjLIvFjvbja9IV4/TpN\n1ztGdtudfXQ0hmhBqS/qagw=\n-----END CERTIFICATE-----"}'
volumes:
  db_data:

