name: Deploy-to-Prod

on:
  push:
    branches:
      - adonis
  release:
    types:
      - published

env:
  DOCKER_REGISTRY: ghcr.io/lopenling/application-backend
  RELEASE_TAG: $(echo $GITHUB_REF | cut -d '/' -f3)

jobs:
  # build-and-push-image:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4

  #   - name: Login to GitHub Container Registry
  #     uses: docker/login-action@v3
  #     with:
  #       registry: ${{ env.DOCKER_REGISTRY }}
  #       username: ${{ github.actor }}
  #       password: ${{ github.token }}

  #   # Build and push container
  #   - name: Build and push container
  #     run: |
  #       docker build -t ${{ env.DOCKER_REGISTRY }}:${{ env.RELEASE_TAG }} .
  #       docker push ${{ env.DOCKER_REGISTRY }}:${{ env.RELEASE_TAG }}

  deploy_containers:
    runs-on: ubuntu-latest
    # needs: build-and-push-image
    steps:
      # Pull and start new containers on production
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        env:
          APP_KEY: ${{ secrets.PROD_APP_KEY }}
          DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          SMTP_PASSWORD: ${{ secrets.PROD_SMTP_PORT }}
        with:
          host: 213.199.45.162
          username: deployer
          command_timeout: 5m
          key: ${{ secrets.PROD_DEPLOYER_KEY }}
          envs: APP_KEY,DB_PASSWORD,SMTP_PASSWORD
          script_stop: true
          script: |
            echo ${{ env.DOCKER_REGISTRY }}:${{ env.RELEASE_TAG }}
            docker login ${{ env.DOCKER_REGISTRY }} --username ${{ github.actor }} --password ${{ github.token }}
            docker pull ${{ env.DOCKER_REGISTRY }}:${{ env.RELEASE_TAG }}
            docker stop application-backend || true
            docker rm application-backend  || true
            docker run -d --name application-backend --restart always \
              -e APP_KEY="$APP_KEY" \
              -e DB_HOST="127.0.0.1" \
              -e DB_PORT="5432" \
              -e DB_USER="lopenling" \
              -e DB_PASSWORD="$DB_PASSWORD" \
              -e DB_DATABASE="lopenling" \
              -e SMTP_HOST="smtp.eu.mailgun.org" \
              -e SMTP_PORT="465" \
              -e SMTP_USERNAME="application-backend@mg.lopenling.com" \
              -e SMTP_PASSWORD="$SMTP_PASSWORD" \
              --network=host \
              ${{ env.DOCKER_REGISTRY }}:${{ env.RELEASE_TAG }}
