name: Node.js App CI/CD

on:
  push:
    branches:
      - deploy-script
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.LINODE_USER_NAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          script: whoami