name: Node.js App CI/CD

on:
  push:
    branches:
      - hasura-jwt-token
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        env:
          HASURA_GRAPHQL_ADMIN_SECRET: ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_GRAPHQL_JWT_SECRET: ${{ secrets.HASURA_GRAPHQL_JWT_SECRET }}
          HASURA_ENDPOINT: ${{ secrets.HASURA_ENDPOINT }}
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.LINODE_USER_NAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          script: |
            cd Padma-Dictionary-Service/
            git pull origin hasura-jwt-token
            cd setup-prod/
            chmod +x setup-prod.sh
            ./setup-dev.sh
            cd .. 
            cd hasura-api-server/
            chmod +x ./setup-dev/setup-prod.sh
            ./setup-dev/setup-prod.sh