name: Node.js App CI/CD

on:
  push:
    branches:
      - deploy-script
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Start Container
        run: |
          cd hasura-api-server
          chmod +x ./setup-dev/setup-dev.sh
          ./setup-dev/setup-dev.sh

      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.LINODE_USER_NAME }}
          key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
          script: |
            cd hasura-api-server
            chmod +x ./setup-dev/setup-dev.sh
            ./setup-dev/setup-dev.sh